[target.thumbv6m-none-eabi]
# 使用 probe-rs 烧录；若用 Pico 拖拽 UF2，可改为 elf2uf2-rs
runner = "probe-rs run --chip RP2040"

# 阻断父目录 mxd_tools/.cargo/config.toml 的主机端 env 继承
[env]
LIBCLANG_PATH = { unset = true }
OPENCV_INCLUDE_PATHS = { unset = true }
OPENCV_LINK_PATHS = { unset = true }
OPENCV_LINK_LIBS = { unset = true }
OPENCV_MSVC_CRT = { unset = true }

[build]
target = "thumbv6m-none-eabi"

[unstable]
build-std = ["core"]
