[package]
edition      = "2024"
name         = "mxd-usb-hid"
rust-version = "1.88"
version      = "0.1.0"

[[bin]]
name = "usb-device"
path = "./src/bin/main.rs"

[dependencies]
embassy-executor = { version = "0.10", features = ["executor-thread", "platform-cortex-m"] }
embassy-rp = { version = "0.10", features = ["time-driver", "rp2040", "critical-section-impl", "rt", "executor-thread"] }
embassy-usb = { version = "0.6" }
embassy-time = { version = "0.5" }
embassy-futures = { version = "0.1" }
usbd-hid = "0.10.1"
cortex-m = "0.7"
cortex-m-rt = "0.7"
critical-section = "1.2.0"
panic-halt = "0.2"
static_cell = "2"
portable-atomic = { version = "1", features = ["unsafe-assume-single-core"] }

[profile.dev]
opt-level = "s"

[profile.release]
codegen-units = 1
debug         = 2
lto           = "thin"
opt-level     = "s"
